- name: Setup Nexus
  hosts: all
  become: yes
  vars_files:
  - vars.yml
  vars:
  - nexus_annonymous_access: true

  pre_tasks:
  - name: Ensure necessary packages are present
    apt:
        name:
          - wget
          - apt-transport-https
          - gpg
        state: present
        update_cache: yes

  - name: Download the Eclipse Adoptium GPG key and add to trusted keyring
    apt_key:
        url: https://packages.adoptium.net/artifactory/api/gpg/key/public
        state: present

  - name: Configure the Eclipse Adoptium apt repository
    shell: |
        echo "deb https://packages.adoptium.net/artifactory/deb $(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release) main" > /etc/apt/sources.list.d/adoptium.list

  - name: Update apt cache
    apt:
        update_cache: yes

  - name: Install Temurin 17 JDK
    apt:
        name: temurin-17-jdk
        state: present

  roles:
  - role: ansible-thoteam.nexus3-oss