---
version: '2'
services:
  nexus:
    build:
      context: nexus
      dockerfile: Dockerfile
    image: nexus-1
    ports: 
    - 8081:8081
  jenkins:
    build:
      context: jenkins
      dockerfile: Dockerfile
      args:
        jenkins_user: admin
        jenkins_password: admin
        jenkins_plugins: |
          credentials 
          credentials-binding 
          golang locale 
          git 
          timestamper 
          nexus-artifact-uploader 
          pipeline-groovy-lib 
          workflow-basic-steps 
          workflow-cps 
          workflow-durable-task-step 
          workflow-job 
          workflow-multibranch 
          pipeline-build-step 
          pipeline-input-step 
          pipeline-milestone-step 
          pipeline-stage-step 
          pipeline-stage-view
          pipeline-model-definition 
          configuration-as-code
        java_opts: "-Djenkins.install.runSetupWizard=false"
# pipeline
    image: jenkins-1
    ports: 
    - 83:8080
    volumes:
    - jenkins-home:/var/jenkins_home
    # depends_on:
    # - nexus
volumes:
  jenkins-home:
  nexus-data: