Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian11"
    config.vm.synced_folder  ".", "/vagrant", disabled: false
    config.vm.network "private_network", ip: "192.168.33.100"
    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.network "forwarded_port", guest: 81, host: 8081
        config.vm.define "dockercompose" do |master|
            master.vm.hostname = "dockercompose.vm"
            master.vm.provider "virtualbox" do |vb|
                vb.memory = 2048
                vb.cpus   = 2
            end
            master.vm.provision "shell", inline: <<-shell
                sudo apt-get update
                sudo apt install -y docker.io docker-compose
                sudo usermod -a -G docker vagrant
            shell
        end
end 