- name: master
  become: yes
  hosts: all

  tasks:
    - name: install sshpass
      become: yes
      yum:
        name: sshpass
        state: present

    - name: disable key check
      become: yes
      ini_file:
        path: /etc/ansible/ansible.cfg
        section: defaults
        option: host_key_checking
        value: False

- name: install  master
  become: yes
  hosts: localhost

  tasks:
    - name: add repository master puppetserver
      dnf:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
        state: present
    
    - name: add repository to master
      dnf:
        name: https://yum.puppetlabs.com/puppet-release-el-8.noarch.rpm
        state: present
    
    - name: install puppetserver
      yum:
        name: puppetserver
        state: latest 
    
    - name: stop firewalld
      service:
        name: firewalld
        state: stopped

    - name: add hosts slave1
      lineinfile:
        path: /etc/hosts
        line: '192.168.33.11 slave1.puppet'
        
    - name: add hosts slave2
      lineinfile:
        path: /etc/hosts
        line: '192.168.33.12 slave2.puppet'
    
    - name: install r10k
      package:
        name: r10k
        state: present
        executable: /opt/puppetlabs/puppet/bin/gem
    
    - name: resize memory
      replace:
        path: /etc/sysconfig/puppetserver
        regexp: '-Xms2g -Xmx2g'
        replace: '-Xms256m -Xmx256m'
    
    - name: adds puppet.config
      blockinfile:
        path: /etc/puppetlabs/puppet/puppet.conf
        block: |
          [agent]
        insertafter: EOF
        
    - name: add puppet.config
      blockinfile:
        path: /etc/puppetlabs/puppet/puppet.conf
        block: |
          server = master.puppet
        insertafter: '\[agent\]'    
    
    - name: start puppetserver
      service:
        name: puppetserver
        state: started

    - name: start puppet
      service:
        name: puppet
        state: started

    - name: add host my conf
      get_url:
        url: https://raw.githubusercontent.com/Stanisz1/devops-hometasks/master/03-puppet/autosign.conf 
        dest: /etc/puppetlabs/puppet/autosign.conf 
        mode: '0644'
    
    - name: download my r10k.yaml 
      get_url:
        url: https://raw.githubusercontent.com/Stanisz1/devops-hometasks/master/03-puppet/r10k.yaml
        dest: /etc/r10k.yaml 
        mode: '0644'  

    - name: activate r10k
      command: '/opt/puppetlabs/puppet/bin/r10k deploy environment -p'
      become: true
