---
- name: Install Puppet agent on slave1 and slave2
  become: yes
  hosts: slave1, slave2
  tasks:
     - name: add repositoriy agent slave1
       shell:  rpm -Uvh https://yum.puppet.com/puppet6-release-el-8.noarch.rpm

     - name: install puppet_agent
       yum:
         name: puppet-agent
         state: latest

     - name: adds puppet.config
       lineinfile:
        path: /etc/puppetlabs/puppet/puppet.conf
        line: "[agent]"
    
     - name: add puppet.config
       lineinfile:
        path: /etc/puppetlabs/puppet/puppet.conf
        line: "server = master.puppet"

     - name: add hosts master.puppet
       lineinfile:
        dest: /etc/hosts
        line: '192.168.33.10 master.puppet'
     
     - name: Start puppet service
       service:
         name: puppet
         state: started

     - name: Stop firewalld service
       service:
         name: firewalld
         state: stopped



- name: all servs
  become: yes
  hosts: all
  tasks:
    - name: install sshpass
      become: yes
      yum:
        name: sshpass
        state: present

    - name: disable key check
      ini_file:
        path: /etc/ansible/ansible.cfg
        section: defaults
        option: host_key_checking
        value: False


- name: master-nginx-puppet
  become: yes
  hosts: localhost
  tasks:
    - name: install nginx
        become: yes
        yum:
          name: nginx
          state: latest


    - name: add statyc and dynamic in nginx
      become: yes
      blockinfile:
        path: /etc/nginx/sites-available/localhost
        create: true
        block: |
          server {
              listen 80;
              listen [::]:8080;
              server_name 192.168.33.10;
              location / {
                  proxy_pass http://192.168.33.11:80;
              }
              
              location / {
                  proxy_pass http://192.168.33.12:80;
              }
              
          }
    
    - name: enabled sites
      become: yes
      file:
        src: /etc/nginx/sites-available/localhost
        dest: /etc/nginx/sites-enabled/localhost
        state: link
        owner: root
        group: root
        force: yes

    - name: restart nginx
      become: yes
      systemd:
        state: restarted
        daemon_reload: true
        name: nginx
  
    - name: Disabling SELinux permissive
      command: sed -i 's/SELINUX=permissive/SELINUX=disabled/g' /etc/selinux/config

    - name: Disabling SELinux enforcing
      command: sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config

    - name: systemctl enabled nginx
      systemd:
        name: nginx
        enabled: yes

    - name: restart
      command: shutdown -r now



- name: install master
  hosts: localhost
  become: yes
  tasks:
    - name: add repositoriy  master puppetserver
      shell:  sudo dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    
    - name: add repositoriy to master 
      shell: sudo dnf -y install https://yum.puppetlabs.com/puppet-release-el-8.noarch.rpm
    
    - name: install puppetserver
      become: yes
      yum:
        name: puppetserver
        state: latest 
    
    - name: stop firewalld
      service:
        name: firewalld
        state: stopped

    - name: add hosts slave1
      lineinfile:
        path: /etc/hosts
        line: '192.168.33.11 slave1.puppet'
        
    - name: add hosts slave2
      lineinfile:
        path: /etc/hosts
        line: '192.168.33.12 slave2.puppet'

    - name: add hosts slave2
      lineinfile:
        path: /etc/hosts
        line: '192.168.33.13 mineserver.puppet'    
    
    - name: install r10k
      shell: sudo /opt/puppetlabs/puppet/bin/gem install r10k
    
    - name: resize memory
      replace:
        path: /etc/sysconfig/puppetserver
        regexp: '-Xms2g -Xmx2g'
        replace: '-Xms256m -Xmx256m'
    
    - name: adds puppet.config
      blockinfile:
        path: /etc/puppetlabs/puppet/puppet.conf
        block: |
          [agent]
        insertafter: EOF
        
    - name: add puppet.config
      blockinfile:
        path: /etc/puppetlabs/puppet/puppet.conf
        block: |
          server = master.puppet
        insertafter: '\[agent\]'    
    
    - name: start puppetserver
      service:
        name: puppetserver
        state: started

    - name: start puppet
      service:
        name: puppet
        state: started

    - name: add host my conf
      become: yes
      get_url:
        url: https://raw.githubusercontent.com/Stanisz1/devops-hometasks/master/03-puppet/autosign.conf 
        dest: /etc/puppetlabs/puppet/autosign.conf 
        mode: '0644'
    
    - name: download my r10k.yaml 
      become: yes
      get_url:
        url: https://raw.githubusercontent.com/Stanisz1/devops-hometasks/master/03-puppet/r10k.yaml
        dest: /etc/r10k.yaml 
        mode: '0644'  

    - name: active r10k
      command: /opt/puppetlabs/puppet/bin/r10k deploy environment -p
      become: yes