---

- name: Install Puppet agent on slave1 and slave2
  become: yes
  hosts: slave, mineserver
  tasks:

    - name: add repositoriy agent slave1
       shell:  rpm -Uvh https://yum.puppet.com/puppet7-release-el-8.noarch.rpm

    - name: add hosts
      lineinfile:
        path: /etc/hosts
        line: '192.168.33.10 master.puppet puppet'

    - name:  puppet-server
      lineinfile:
        path: /etc/puppetlabs/puppet/puppet.conf
        line: "{{item}}"
      with_items:
         - '[agent]'
         - server = master.puppet
         - runinterval = 1m

    - name: enable Puppetagent
      service:
        name: puppet
        enabled: yes
        state: started
     - name: install puppet_agent
       yum:
         name: puppet-agent
         state: latest

     - name: Stop firewalld service
       service:
         name: firewalld
         state: stopped



- name: install master
  hosts: master
  become: yes
  tasks:
    - name: add repositoriy  master puppetserver
      shell:  sudo dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    
    - name: add repositoriy to master 
      shell: sudo dnf -y install https://yum.puppetlabs.com/puppet-release-el-8.noarch.rpm
    
    - name: Pkg installation
      ansible.builtin.yum:
        name:
          - puppetserver
          - gem
        state: present

    - name: Installing r10k (shell)
      ansible.builtin.shell:
        cmd: |
          yum module reset -y ruby
          yum install -y @ruby:2.6
          gem install r10k

    - name: stop firewalld
      service:
        name: firewalld
        state: stopped

    - name: add hosts slave1
      lineinfile:
        path: /etc/hosts
        line: "{{item}}"
      with_items:
         - '192.168.33.10 master.puppet'
         - '192.168.33.11 slave1.puppet'
         - '192.168.33.12 slave2.puppet'
         - '192.168.33.13 mineserver.puppet'   
    
    - name: resize memory
      replace:
        path: /etc/sysconfig/puppetserver
        regexp: '-Xms2g -Xmx2g'
        replace: '-Xms256m -Xmx256m'
    
    - name: set master.puppet agent 
      ini_file:
        path: /etc/puppetlabs/puppet/puppet.conf
        section: "{{ item.sect }}"
        option: "{{ item.option }}"
        value: "{{ item.value }}"
      with_items:
        - { sect: "server", option: "autosign", value: "true" }
        - { sect: "agent", option: "server", value: "master.puppet" }
        - { sect: "agent", option: "runinterval", value: "1m" }

    - name: Stop and disable firewalld
      service:
        name: firewalld
        state: stopped
        enabled: False

    - name: start puppetserver
      service:
        name: puppetserver
        enabled: yes
        state: started

    - name: start puppet
      service:
        name: puppet
        enabled: yes
        state: started

    
    - name: create directory
      become: yes
      file: 
        path: /etc/puppetlabs/r10k/
        state: directory

    - name: download my r10k.yaml 
      become: yes
      get_url:
        url: https://raw.githubusercontent.com/Stanisz1/devops-hometasks/master/03-puppet/r10k.yaml
        dest: /etc/puppetlabs/r10k/r10k.yaml 
        mode: '0644'  

    - name: auto deploy environment(cron)
      cron:
        name: "deploy environment"
        minute: "0-59"
        hour: "*"
        job: "r10k deploy environment -p"