---
- name: Configure SSH on slave
  hosts: all
  tasks:
    - name: Update sshd_config
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication no'
        line: 'PasswordAuthentication yes'
      become: yes

    - name: Restart SSH service
      service:
        name: sshd
        state: restarted

- name: Install Puppet agent on slave1 and slave2
  become: yes
  hosts: slave1, slave2
  tasks:
     - name: add repository agent slave1
       dnf:
         name: https://yum.puppet.com/puppet6-release-el-8.noarch.rpm
         state: present
     
     - name: Install puppet-agent package
       yum:
         name: puppet-agent
         state: latest

     - name: Add puppet.config
       lineinfile:
        path: /etc/puppetlabs/puppet/puppet.conf
        regexp: '^#?[\s]*server = .*$'
        line: 'server = master.puppet'
       become: yes

     - name: Add master.puppet to hosts file
       lineinfile:
        path: /etc/hosts
        regexp: '^192\.168\.33\.10.*$'
        line: '192.168.33.10 master.puppet'
       become: yes

     - name: Start puppet service
       service:
        name: puppet
        state: started

     - name: Stop firewalld service
       service:
        name: firewalld
        state: stopped
