---
- name: Configure SSH on slave
  hosts: all
  tasks:
    - name: Update sshd_config
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication no'
        line: 'PasswordAuthentication yes'
      become: yes

    - name: Restart SSH service
      service:
        name: sshd
        state: restarted
