# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos8s"
  config.vm.synced_folder ".", "/vagrant", disabled: false
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  config.vm.define "slave1.puppet" do |slave1|
    slave1.vm.hostname = "slave1.puppet"
    slave1.vm.network "private_network", ip: "192.168.33.11"
    slave1.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "slave.yaml"
      ansible.become = true
    end
  end

  config.vm.define "slave2.puppet" do |slave2|
    slave2.vm.hostname = "slave2.puppet"
    slave2.vm.network "private_network", ip: "192.168.33.12"
    slave2.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "slave.yaml"
      ansible.become = true
    end
  end
  
  config.vm.define "master.puppet" do |master|
    master.vm.hostname = "master.puppet"
    master.vm.network "private_network", ip: "192.168.33.10"
    master.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "master.yaml"
      ansible.become = true
    end
  end
end
