# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos8s"
  config.vm.synced_folder ".", "/vagrant", disabled: false
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  config.vm.provision "shell", inline: <<-shell
    sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
    sudo systemctl restart sshd.service
  shell

  config.vm.define "slave1.puppet" do |slave|
    slave.vm.hostname = "slave1.puppet"
    slave.vm.network "private_network", ip: "192.168.33.11"
  end

  config.vm.define "slave2.puppet" do |slave|
    slave.vm.hostname = "slave2.puppet"
    slave.vm.network "private_network", ip: "192.168.33.12"  
  end

  config.vm.define "mineserver.puppet" do |mineserver|
    mineserver.vm.hostname = "mineserver.puppet"
    mineserver.vm.network "private_network", ip: "192.168.33.13"
    
  end
  
  config.vm.define "master.puppet" do |master|
    master.vm.hostname = "master.puppet"
    master.vm.network "private_network", ip: "192.168.33.10"
    master.vm.network "forwarded_port", guest: 80, host: 8080
    master.vm.network "forwarded_port", guest: 8080, host: 8081
    master.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook.yaml"
      ansible.limit = 'all'
      ansible.inventory_path = "inventory.yaml"
      ansible.become = true
    end
  end
end
