Vagrant.configure("2") do |config|

    config.vm.box = "generic/debian11"
    config.vm.synced_folder  ".", "/vagrant", disabled: false
    config.vm.network "private_network", ip: "192.168.33.83"
  
    config.vm.provider "virtualbox" do |vb|
        vb.memory = 3072
        vb.cpus   = 2
    end
    config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y ca-certificates curl gnupg lsb-release gnome-core gnome
    curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian \
        $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    apt-get update
    apt-get install -y docker-ce docker-ce-cli containerd.io
    usermod -aG docker vagrant
    sed -i "s/^#force_color_prompt=yes\$/force_color_prompt=yes/g" /home/vagrant/.bashrc
    sed -i "s/^#alias ll='ls -l'\$/alias ll='ls -la'/g" /home/vagrant/.bashrc
    systemctl enable gdm3
    systemctl start gdm3        
    SHELL
end   