apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wcg
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: development

  source:
    repoURL: https://github.com/Stanisz1/devops-hometasks.git
    targetRevision: master
    path: 12-helm/wcg

    helm:
      # Extra parameters to set (same as setting through values.yaml, but these take precedence)
      parameters:
        - name: "wcg-svc"
          value: "8888"
      # - name: "replicaCount"
      #   value: "4"

      # Helm values files for overriding values in the helm chart
      # The path is relative to the spec.source.path directory defined above
      # valueFiles:
      # - values-dev.yaml

      # Values file as block file
      values: |
        # replicaCount: 2

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: wcg

  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
