apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: wcg
  labels:
    app: wcg
spec:
  rules:
    - host: wcggg.net.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: wcg
                port:
                  number: 8888
