---
- name: jenkins
  hosts: jenkins
  become: yes
  roles:
    - jenkins

  tasks:
  - name: Install jq
    apt:
      name: jq
      state: present     


- name: Manage Nexus
  hosts: nexus
  become: yes

  tasks:
  - name: Add key
    apt_key:
      url: https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public


  - name: Add repository
    apt_repository:
      repo: deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ buster main
      state: present
      update_cache: true

  - name: Install Java
    apt:
      name: adoptopenjdk-8-hotspot
      state: present

  - name: Install and config Nexus
    include_role:
      name: ansible-thoteam.nexus3-oss
    vars:
      nexus_min_heap_size: "1024M"
      nexus_admin_password: 'admin'
      nexus_delete_default_repos: True
      nexus_local_users:
        - username: uploader
          first_name: Nexus
          last_name: Uploader
          email: jenkins@gmail.com
          password: "uploader"
          roles:
            - nx-admin
      nexus_config_raw: true
      nexus_repos_raw_hosted:
        - name: word-cloud-build
          version_policy: release
          write_policy: allow_once
          blob_store: default

- name: Slave's manage
  hosts:
    - staging
    - production
  become: yes

  tasks:

    - name: Create dir for service
      ansible.builtin.file:
        path: "/opt/wordcloud/"
        state: directory
        owner: vagrant
        group: vagrant
        mode: 0755

    - name: Create service
      ansible.builtin.copy:
        src: "roles/jenkins/files/slaves/wordcloud.service"
        dest: "/etc/systemd/system/wordcloud.service"