- name: Setup Nexus
  hosts: nexus
  become: yes
  # vars_files:
  # - /vagrant/nexus/vars/vars.yml
  # vars:
  # - nexus_annonymous_access: true

  pre_tasks:
  - name: Add key
    apt_key:
      url: https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public
  
  - name: Add repository
    apt_repository:
      repo: deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ buster main
      state: present
      update_cache: true

  - name: Install Java
    apt:
      name: adoptopenjdk-8-hotspot
      state: present

  roles:
  - role: ansible-thoteam.nexus3-oss