---
- name: Configure Staging and Prod
  hosts: staging, prod
  become: yes
  
  tasks:
  - name: install essential packages
    apt:
      pkg:
      - jq
      - build-essential
      - default-jre
      - git
      - mc
      - curl
      state: present
      update_cache: true

  - name: create directory /opt/wordcloud
    file:
      path: /opt/wordcloud
      state: directory
      mode: '0755'
      owner: vagrant

  - name: copy wordcloud.service
    copy:
      dest: /etc/systemd/system/wordcloud.service
      content: |
        [Unit]
        Description=Word Cloud Generator

        [Service]
        WorkingDirectory=/opt/wordcloud
        ExecStart=/opt/wordcloud/word-cloud-generator

        [Install]
        WantedBy=multi-user.target

  - name: start and enable wordcloud.service
    service:
      name: wordcloud.service
      state: started
      enabled: yes
  
  - name: Enable password authentification
    replace:
      path: /etc/ssh/sshd_config
      regexp: '^PasswordAuthentication no$'
      replace: 'PasswordAuthentication yes'
    notify: restart sshd
  
  - name: Set password for vagrant user
    user:
      name: vagrant
      password: "{{ 'vagrant'|password_hash('sha512') }}"
  
  handlers:
  - name: restart sshd
    service:
      name: sshd
      state: restarted