---
- name: Nginx Proxy
  hosts: nginx

  tasks:
    - name: install nginx
      become: yes
      apt:
        pkg:
        - nginx
        state: present

    - name: add statyc and dynamic in nginx
      become: yes
      blockinfile:
        path: /etc/nginx/sites-available/localhost
        create: true
        block: |
          server {
              listen 80;
              listen [::]:8080;
              server_name 192.168.33.11;
              location /index.html {
                  proxy_pass http://192.168.33.12:80;
              }
              
              location /index.php {
                  proxy_pass http://192.168.33.13:80;
              }
              
          }
    
    - name: enabled sites
      become: yes
      file:
        src: /etc/nginx/sites-available/localhost
        dest: /etc/nginx/sites-enabled/localhost
        state: link
        owner: root
        group: root
        force: yes

    - name: restart nginx
      become: yes
      systemd:
        state: restarted
        daemon_reload: true
        name: nginx