Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian11"
  config.vm.synced_folder  ".", "/vagrant", disabled: false
  config.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
  end

  config.vm.define "static" do |slave|
      slave.vm.network "private_network", ip: "192.168.33.12"

      slave.vm.provision "ansible_local" do |ansible|
          ansible.playbook = "playbook.yaml"
          ansible.become = true
      end
  end

  config.vm.define "dynamic" do |slave|
      slave.vm.network "private_network", ip: "192.168.33.13"

      slave.vm.provision "ansible_local" do |ansible|
          ansible.playbook = "playbook.yaml"
          ansible.become = true
      end
  end

  config.vm.define "nginx", primary: true do |master|
      master.vm.network "private_network", ip: "192.168.33.11"
      master.vm.provision "shell", inline: <<-SHELL
            apt-get update
            apt-get install -y vim mc ansible sshpass
        SHELL
      master.vm.provision "ansible_local" do |ansible|
          ansible.playbook = "nginx.yaml"
          ansible.limit = 'all'
          ansible.inventory_path = "inventory"
      end
  end
end

