replicas: 1
service:
  port: 8888
  name: wcg
  protocol: TCP

container:
  port: 8888
  portName: http
  label: wcg
  name: wcg

image:
  repository: ghcr.io/stanisz1/wcg:d0e68ba67d59152b5c5b2b5f9f5d1d56140fa573
  name: github-pull-secret
  imagePullPolicy: Always
  resources: {}

ingress:
  enabled: true
  host: wcg.local.com
  paths:
    path: "/"
    pathType: Prefix
