replicas: 1
service:
  port: 8888
  name: wcg
  protocol: TCP

container:
  port: 8888
  portName: http
  label: wcg
  name: wcg

image:
  repository: ghcr.io/stanisz1/wcg
  name: github-pull-secret
  imagePullPolicy: Always
  tag: ""
  resources: {}

ingress:
  enabled: true
  host: wcg.local.com
  paths:
    path: "/"
    pathType: Prefix
