---
#- name: Wait for Jenkins to start up
#  uri:
#    url: http://localhost:8080
#    status_code: 200
#    user: "admin"
#    password: "admin"
#    timeout: 5
#    force_basic_auth: yes
#  register: jenkins_service_status
#  retries: 10
#  delay: 5
#  until: >
#     'status' in jenkins_service_status and
#     jenkins_service_status['status'] == 200

#- name: Check Jenkins status
#  debug:
#    msg: "Jenkins status: {{ jenkins_service_status['status'] }}"

- name: Copy credentials .xml file
  ansible.builtin.unarchive:
    src: credentials.tar.gz
    dest: /var/lib/jenkins/

#- name: Restart Jenkins
#  systemd:
#    name: jenkins
#    state: restarted
#    daemon_reload: true