---

#- name: Wait for Jenkins to start up
#  uri:
#    url: http://localhost:8080
#    status_code: 200
#    user: "admin"
#    password: "admin"
#    timeout: 5
#    force_basic_auth: yes
#  register: jenkins_service_status
#  retries: 10
#  delay: 5
#  until: >
#     'status' in jenkins_service_status and
#     jenkins_service_status['status'] == 200

#- name: Check Jenkins status
#  debug:
#    msg: "Jenkins status: {{ jenkins_service_status['status'] }}"

- name: Copy SSH plugin file
  ansible.builtin.copy:
    src: org.jvnet.hudson.plugins.SSHBuildWrapper.xml
    dest: /var/lib/jenkins/org.jvnet.hudson.plugins.SSHBuildWrapper.xml
    owner: jenkins
    group: jenkins
    mode: 0644

- name: Copy Golang plugin file
  ansible.builtin.copy:
    src: org.jenkinsci.plugins.golang.GolangBuildWrapper.xml
    dest: /var/lib/jenkins/org.jenkinsci.plugins.golang.GolangBuildWrapper.xml
    owner: jenkins
    group: jenkins
    mode: 0644

- name: Jenkins start
  service:
    name: jenkins
    state: started       

- name: Pause for 1 min
  ansible.builtin.pause:
    minutes: 1

- name: Install Jenkins plugins
  jenkins_plugin:
    name: "{{ item }}"
    url_username: "admin"
    url_password: "admin"
    state: present
    timeout: 120
    with_dependencies: yes
  with_items:
    - golang
    - git
    - nexus-artifact-uploader
    - ssh
    - build-essential
    - default-jre
    - jq
    - python3-pip
  #when: jenkins_service_status['status'] == 200

#- name: Restart Jenkins
#  systemd:
#    name: jenkins
#    state: restarted
#    daemon_reload: true