---
- name: master
  hosts: all
  become: yes

  vars:
    port_80: 80
    port_8080: 8080
    mst: 000-default

  tasks:
    - name: Install Apache
      apt:
        pkg:
        - apache2
        - php
        - libapache2-mod-php
        state: present

    - name: Create a directory /var/www/html/p
      ansible.builtin.file:
        path: /var/www/html/p
        state: directory
        mode: '0755'

    - name: Copy file /var/www/html/index.html
      ansible.builtin.copy:
        src: /vagrant/index.html
        dest: /var/www/html/index.html
        force: true
        owner: root
        group: root
        mode: '0644'

    - name: Copy file /var/www/html/p/index.php
      ansible.builtin.copy:
        src: /vagrant/index.php
        dest: /var/www/html/p/index.php
        force: true
        owner: root
        group: root
        mode: '0644'

    - name: enabled mod_rewrite
      apache2_module:
        name: rewrite
        state: present
      notify:
        - restart apache2

    - name: apache2 listen on port {{ port_80 }}
      lineinfile:
        dest: /etc/apache2/ports.conf
        regexp: "^Listen 80$"
        line: "Listen {{ port_80 }}"
        state: present
      notify:
        - restart apache2

    - name: apache2 listen on port {{ port_8080 }}
      lineinfile:
        dest: /etc/apache2/ports.conf
        regexp: "^Listen 8080"
        line: "Listen {{ port_8080 }}"
        state: present
        insertafter: '^Listen 8080$'
      notify:
        - restart apache2

    - name: apache2 virtualhost on port {{ port_80 }}
      lineinfile:
        dest: /etc/apache2/sites-available/000-default.conf
        regexp: "^<VirtualHost *:"
        line: "<VirtualHost *:{{ port_80 }}>"
      notify:
        - restart apache2

    - name: create virtual host file
      template:
        src: /vagrant/000-default.conf
        dest: /etc/apache2/sites-available/{{ mst }}.conf

    - name: generate symlinks to {{ mst }}.conf
      command: a2ensite {{ mst }}
      args:
        creates: /etc/apache2/sites-enabled/{{ mst }}.conf
      notify:
        - restart apache2

  handlers:
    - name: restart apache2
      service:
        name: apache2
        state: restarted
