Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian9" 
  
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yaml"
  end

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 8080, host: 8081
  
  config.vm.provider "virtualbox" do |vb| 
    vb.name = "task_2" 
    vb.memory = "512" 
  end
end