Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian11"
    config.vm.synced_folder ".", "/vagrant", disabled: false
    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.network "forwarded_port", guest: 8080, host: 8081
    config.vm.network "private_network", ip: "192.168.33.10"
    
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
    
    config.vm.define "master", primary: true do |master|
      master.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y ansible sshpass
      SHELL
    end
    config.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "playbook.yaml"
    end

  end
  