Vagrant.configure("2") do |config|
  # названия бокса в vagrant claude
  config.vm.box = "atrohov97/centostask1" 
  # Проксируем порты
  # пробрасываем порты для доступа к сайту из локальной сети и с локального компьютера
  config.vm.network "private_network", ip: "192.168.33.10" # присваиваем ВМ статический IP-адрес в локальной сети 
  
  

  config.vm.provider "virtualbox" do |vb| # конфигурируем провайдера VirtualBox
    vb.name = "centos_task_1" # задаем имя ВМ
    vb.memory = "512" # задаем количество оперативной памяти для ВМ
  end

  config.vm.provision "shell", inline: <<-SHELL # выполняем команды в Shell при создании ВМ
    sudo yum update
    sudo yum install -y git # устанавливаем Git
    sudo yum install -y httpd  php # устанавливаем  php httpd
    
  SHELL

  config.vm.provision "file", run: "always", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"
  config.vm.provision "file", run: "always", source: "~/.ssh/id_rsa", destination: "~/.ssh/id_rsa"
 
end
