Vagrant.configure("2") do |config|
  # выбираем базовый образ Debian 9
  config.vm.box = "generic/debian9" 
  # пробрасываем порты для доступа к сайту из локальной сети и с локального компьютера
  config.vm.network "private_network", ip: "192.168.33.10" # присваиваем ВМ статический IP-адрес в локальной сети 
  

  config.vm.provider "virtualbox" do |vb| # конфигурируем провайдера VirtualBox
    vb.name = "deb_task_1" # задаем имя ВМ
    vb.memory = "512" # задаем количество оперативной памяти для ВМ
  end

  config.vm.provision "shell", inline: <<-SHELL # выполняем команды в Shell при создании ВМ
    sudo apt-get update
    sudo apt-get install -y git # устанавливаем Git
    git config --global user.name "Stanisz1" # задаем имя пользователя для Git
    git config --global user.email "atrohov97@gmail.com" # задаем email пользователя для Git
    git config --list # выводим настройки Git
    sudo apt-get install -y apache2 # устанавливаем Apache2
    sudo apt-get install unzip
    sudo chmod -R 755 /tmp/
    sudo wget https://github.com/Stanisz1/devops-hometasks/archive/refs/heads/master.zip -O /tmp/git.zip
    sudo unzip /tmp/git.zip -d /tmp/
    sudo apt-get install -y php # устанавливаем PHP
    sudo rm -ivf /var/www/html/index.html # удаляем индексную страницу Apache
  
      sudo cp /tmp/devops-hometasks-master/01-vagrant/index.html /var/www/html/
      sudo mkdir -p /var/www/html/php
      sudo cp /tmp/devops-hometasks-master/01-vagrant/index.php /var/www/html/php/
      sudo cp /tmp/devops-hometasks-master/01-vagrant/apache2.conf /etc/apache2/
      sudo cp /tmp/devops-hometasks-master/01-vagrant/ports.conf /etc/apache2/
      sudo cp /tmp/devops-hometasks-master/01-vagrant/000-default.conf /etc/apache2/sites-enabled/ /etc/apache2/sites-available/
      sudo systemctl restart apache2
  SHELL

  config.vm.provision "file", run: "always", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"
  config.vm.provision "file", run: "always", source: "~/.ssh/id_rsa", destination: "~/.ssh/id_rsa"
end
