Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian9"
  config.vm.synced_folder ".", "/vagrant"

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 8080, host: 8081
  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provider "virtualbox" do |vb|
      vb.name = "gitdemo.vagrant.vm"
      # Customize the amount of memory on the VM:
      vb.memory = "512"
  end

  config.vm.provision "shell", inline: <<-SHELL
      apt update
      apt install -y apache2
      apt install -y php
      apt install -y libapache2-mod-php
      usermod -aG root vagrant
      cp /vagrant/index.html /var/www/html/index.html
      cd /var/www/ && sudo mkdir php
      cp /vagrant/index.php /var/www/php/index.php
      cp /vagrant/000-default.conf /etc/apache2/sites-available/000-default.conf
      cp /vagrant/ports.conf /etc/apache2/ports.conf
      sudo systemctl restart apache2
  SHELL
  
end