unclassified:
  locale:
    systemLocale: en
    ignoreAcceptLanguage: true

credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          scope:    GLOBAL
          id:       slave_creds
          username: vagrant
          password: vagrant

      - usernamePassword:
          scope: GLOBAL
          id: nx-uploader
          username: nx-uploader
          password: nx-uploader

      - usernamePassword:
          scope: GLOBAL
          id: vagrant_staging
          username: vagrant
          password: vagrant

      - usernamePassword:
          scope: GLOBAL
          id: vagrant_production
          username: vagrant
          password: vagrant
tool:
  go:
    installations:
    - name: "go_lang"
      properties:
      - installSource:
          installers:
          - golangInstaller:
              id: "1.16"