Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian11"
  config.vm.provider "virtualbox" do |vb|
      vb.memory = 256
      vb.cpus = 1
    end

  config.vm.synced_folder  ".", "/vagrant", disabled: false

  config.vm.define "staging.vm" do |host|
    host.vm.network "private_network", ip: "192.168.50.55"
    host.vm.provision "shell", inline: <<-SHELL
      sed -i "s/^#force_color_prompt=yes\$/force_color_prompt=yes/g" /home/vagrant/.bashrc
      sed -i "s/^#alias ll='ls -l'\$/alias ll='ls -la'/g" /home/vagrant/.bashrc
      sed -i "s/^PasswordAuthentication no\$/PasswordAuthentication yes/g" /etc/ssh/sshd_config
      service sshd restart
    SHELL
    # host.vm.provision "ansible_local" do |ansible|
    #   ansible.inventory_path = "inventory"
    #   ansible.compatibility_mode = "2.0"
    #   ansible.playbook = "staging.yaml"
    #   ansible.limit = "staging"
    # end
  end

  config.vm.define "production.vm" do |host|
    host.vm.network "private_network", ip: "192.168.50.60"
    host.vm.provision "shell", inline: <<-SHELL
      sed -i "s/^#force_color_prompt=yes\$/force_color_prompt=yes/g" /home/vagrant/.bashrc
      sed -i "s/^#alias ll='ls -l'\$/alias ll='ls -la'/g" /home/vagrant/.bashrc
      sed -i "s/^PasswordAuthentication no\$/PasswordAuthentication yes/g" /etc/ssh/sshd_config
      service sshd restart
    SHELL
    # host.vm.provision "ansible_local" do |ansible|
    #   ansible.inventory_path = "inventory"
    #   ansible.compatibility_mode = "2.0"
    #   ansible.playbook = "production.yaml"
    #   ansible.limit = "production"
    # end
  end

  config.vm.define "nexus.vm" do |nexus|
    nexus.vm.network "private_network", ip: "192.168.50.65"
    nexus.vm.network "forwarded_port", guest: 8081, host: 8091
    nexus.vm.provider("virtualbox"){ |vb| vb.memory = 1600 }
    nexus.vm.provider("virtualbox"){ |vb| vb.cpus = 2 }
    nexus.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y build-essential git wget
        wget https://builds.openlogic.com/downloadJDK/openlogic-openjdk/8u392-b08/openlogic-openjdk-8u392-b08-linux-x64-deb.deb
        apt-get install -y ./openlogic-openjdk-8u392-b08-linux-x64-deb.deb
        rm -R /vagrant/roles/nexus3-oss
        git clone https://github.com/ansible-ThoTeam/nexus3-oss.git /vagrant/roles/nexus3-oss
        
        sed -i "s/^#force_color_prompt=yes\$/force_color_prompt=yes/g" /home/vagrant/.bashrc
        sed -i "s/^#alias ll='ls -l'\$/alias ll='ls -la'/g" /home/vagrant/.bashrc
        sed -i "s/^PasswordAuthentication no\$/PasswordAuthentication yes/g" /etc/ssh/sshd_config
        service sshd restart
      
    SHELL

    # nexus.vm.provision "ansible_local" do |ansible|
    #   ansible.inventory_path = "inventory"
    #   ansible.compatibility_mode = "2.0"
    #   ansible.playbook = "nexus.yaml"
    #   ansible.limit = "nexus"
    #   ansible.become = true
    # end
  end

  config.vm.define "jenkins.vm" do |jenkins|
    jenkins.vm.network "private_network", ip: "192.168.50.50"
    jenkins.vm.provider("virtualbox"){ |vb| vb.memory = 1600 }
    jenkins.vm.provider("virtualbox"){ |vb| vb.cpus = 2 }

    jenkins.vm.provision "ansible_local" do |ansible|
      ansible.inventory_path = "inventory"
      ansible.compatibility_mode = "2.0"
      ansible.playbook = "jenkins.yaml"
      ansible.limit = "all"
      ansible.become = true
    end
  end
end
